import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Helper function to create slug from name
function createSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Comprehensive category data with 50+ main categories and 5-10 subcategories each
const categoryData = [
  {
    name: "Appetizers",
    type: "FOOD",
    subCategories: [
      "Spring Rolls",
      "Samosas",
      "Chicken Wings",
      "Mozzarella Sticks",
      "Bruschetta",
      "Nachos",
      "Onion Rings",
      "Calamari",
      "Garlic Bread",
      "Stuffed Mushrooms",
    ],
  },
  {
    name: "Soups",
    type: "FOOD",
    subCategories: [
      "Tomato Soup",
      "Chicken Soup",
      "Lentil Soup",
      "Minestrone",
      "French Onion",
      "Hot & Sour",
      "Tom Yum",
      "Clam Chowder",
      "Pumpkin Soup",
      "Mushroom Soup",
    ],
  },
  {
    name: "Salads",
    type: "FOOD",
    subCategories: [
      "Caesar Salad",
      "Greek Salad",
      "Garden Salad",
      "Cobb Salad",
      "Caprese Salad",
      "Asian Salad",
      "Quinoa Salad",
      "Fruit Salad",
      "Pasta Salad",
      "Coleslaw",
    ],
  },
  {
    name: "Burgers",
    type: "FOOD",
    subCategories: [
      "Beef Burger",
      "Chicken Burger",
      "Veggie Burger",
      "Cheese Burger",
      "Double Patty",
      "Bacon Burger",
      "Mushroom Swiss",
      "BBQ Burger",
      "Slider",
      "Combo Meal",
    ],
  },
  {
    name: "Pizzas",
    type: "FOOD",
    subCategories: [
      "Margherita",
      "Pepperoni",
      "Hawaiian",
      "Vegetarian",
      "Meat Lovers",
      "BBQ Chicken",
      "Four Cheese",
      "Supreme",
      "Buffalo Chicken",
      "White Pizza",
    ],
  },
  {
    name: "Pasta",
    type: "FOOD",
    subCategories: [
      "Spaghetti",
      "Fettuccine Alfredo",
      "Lasagna",
      "Carbonara",
      "Penne Arrabiata",
      "Mac & Cheese",
      "Ravioli",
      "Pesto Pasta",
      "Bolognese",
      "Seafood Pasta",
    ],
  },
  {
    name: "Sandwiches",
    type: "FOOD",
    subCategories: [
      "Club Sandwich",
      "BLT",
      "Grilled Cheese",
      "Chicken Sandwich",
      "Tuna Sandwich",
      "Veggie Wrap",
      "Panini",
      "French Dip",
      "Reuben",
      "Philly Cheesesteak",
    ],
  },
  {
    name: "Rice Dishes",
    type: "FOOD",
    subCategories: [
      "Biryani",
      "Fried Rice",
      "Pulao",
      "Risotto",
      "Paella",
      "Jambalaya",
      "Rice Bowl",
      "Sushi Rice",
      "Coconut Rice",
      "Khichdi",
    ],
  },
  {
    name: "Curry",
    type: "FOOD",
    subCategories: [
      "Butter Chicken",
      "Chicken Tikka Masala",
      "Korma",
      "Vindaloo",
      "Thai Green Curry",
      "Thai Red Curry",
      "Massaman Curry",
      "Paneer Curry",
      "Fish Curry",
      "Lamb Curry",
    ],
  },
  {
    name: "Grilled Items",
    type: "FOOD",
    subCategories: [
      "BBQ Ribs",
      "Grilled Chicken",
      "Kebabs",
      "Satay",
      "Yakitori",
      "Grilled Fish",
      "Grilled Vegetables",
      "Tandoori Chicken",
      "Steak",
      "Shish Kebab",
    ],
  },
  {
    name: "Seafood",
    type: "FOOD",
    subCategories: [
      "Fish & Chips",
      "Grilled Salmon",
      "Shrimp Scampi",
      "Lobster",
      "Crab Cakes",
      "Sushi",
      "Sashimi",
      "Fish Tacos",
      "Calamari",
      "Mussels",
    ],
  },
  {
    name: "Tacos & Mexican",
    type: "FOOD",
    subCategories: [
      "Beef Tacos",
      "Chicken Tacos",
      "Fish Tacos",
      "Burritos",
      "Quesadillas",
      "Enchiladas",
      "Fajitas",
      "Tostadas",
      "Taco Platter",
      "Nachos Supreme",
    ],
  },
  {
    name: "Asian Specialties",
    type: "FOOD",
    subCategories: [
      "Pad Thai",
      "Lo Mein",
      "Chow Mein",
      "Ramen",
      "Pho",
      "Dumplings",
      "Dim Sum",
      "Sushi Rolls",
      "Teriyaki",
      "General Tso",
    ],
  },
  {
    name: "Indian Bread",
    type: "FOOD",
    subCategories: [
      "Naan",
      "Roti",
      "Paratha",
      "Kulcha",
      "Puri",
      "Bhatura",
      "Tandoori Roti",
      "Garlic Naan",
      "Butter Naan",
      "Cheese Naan",
    ],
  },
  {
    name: "Breakfast",
    type: "FOOD",
    subCategories: [
      "Pancakes",
      "Waffles",
      "French Toast",
      "Eggs Benedict",
      "Omelette",
      "Breakfast Burrito",
      "Bagels",
      "Cereal",
      "Yogurt Parfait",
      "Breakfast Platter",
    ],
  },
  {
    name: "Sides",
    type: "FOOD",
    subCategories: [
      "French Fries",
      "Onion Rings",
      "Coleslaw",
      "Mashed Potatoes",
      "Steamed Vegetables",
      "Rice",
      "Baked Potato",
      "Sweet Potato Fries",
      "Grilled Corn",
      "Garden Salad",
    ],
  },
  {
    name: "Desserts",
    type: "DESSERT",
    subCategories: [
      "Chocolate Cake",
      "Cheesecake",
      "Ice Cream",
      "Tiramisu",
      "Brownies",
      "Cookies",
      "Pie",
      "Mousse",
      "Pudding",
      "Crème Brûlée",
    ],
  },
  {
    name: "Beverages",
    type: "DRINK",
    subCategories: [
      "Soft Drinks",
      "Juice",
      "Iced Tea",
      "Lemonade",
      "Smoothies",
      "Milkshakes",
      "Water",
      "Sparkling Water",
      "Energy Drinks",
      "Sports Drinks",
    ],
  },
  {
    name: "Coffee & Tea",
    type: "DRINK",
    subCategories: [
      "Espresso",
      "Cappuccino",
      "Latte",
      "Americano",
      "Mocha",
      "Macchiato",
      "Black Coffee",
      "Green Tea",
      "Black Tea",
      "Herbal Tea",
    ],
  },
  {
    name: "Steaks",
    type: "FOOD",
    subCategories: [
      "Ribeye",
      "Sirloin",
      "T-Bone",
      "Filet Mignon",
      "New York Strip",
      "Porterhouse",
      "Skirt Steak",
      "Flank Steak",
      "Steak Platter",
      "Surf & Turf",
    ],
  },
  {
    name: "BBQ",
    type: "FOOD",
    subCategories: [
      "BBQ Ribs",
      "Pulled Pork",
      "BBQ Chicken",
      "Brisket",
      "Smoked Sausage",
      "BBQ Platter",
      "BBQ Wings",
      "BBQ Sandwich",
      "Burnt Ends",
      "Smoked Turkey",
    ],
  },
  {
    name: "Vegetarian",
    type: "FOOD",
    subCategories: [
      "Veggie Burger",
      "Falafel",
      "Vegetable Curry",
      "Paneer Dishes",
      "Veggie Pizza",
      "Veggie Wrap",
      "Stuffed Peppers",
      "Eggplant Parmesan",
      "Veggie Stir Fry",
      "Veggie Platter",
    ],
  },
  {
    name: "Vegan",
    type: "FOOD",
    subCategories: [
      "Vegan Burger",
      "Tofu Dishes",
      "Vegan Pizza",
      "Quinoa Bowl",
      "Vegan Curry",
      "Buddha Bowl",
      "Vegan Wrap",
      "Tempeh Dishes",
      "Vegan Pasta",
      "Vegan Stir Fry",
    ],
  },
  {
    name: "Gluten Free",
    type: "FOOD",
    subCategories: [
      "GF Pizza",
      "GF Pasta",
      "GF Bread",
      "GF Burger",
      "GF Salad",
      "GF Rice Dishes",
      "GF Soup",
      "GF Dessert",
      "GF Wraps",
      "GF Breakfast",
    ],
  },
  {
    name: "Kids Menu",
    type: "FOOD",
    subCategories: [
      "Chicken Nuggets",
      "Mini Burger",
      "Mac & Cheese",
      "Grilled Cheese",
      "Pizza Slice",
      "Hot Dog",
      "Fish Sticks",
      "Pasta",
      "Kids Combo",
      "Milk & Cookies",
    ],
  },
  {
    name: "Combo Meals",
    type: "FOOD",
    subCategories: [
      "Burger Combo",
      "Chicken Combo",
      "Pizza Combo",
      "Family Meal",
      "Value Meal",
      "Deluxe Combo",
      "Breakfast Combo",
      "Lunch Special",
      "Dinner Special",
      "Party Pack",
    ],
  },
  {
    name: "Healthy Options",
    type: "FOOD",
    subCategories: [
      "Grilled Chicken Salad",
      "Protein Bowl",
      "Smoothie Bowl",
      "Grain Bowl",
      "Low-Carb Options",
      "Keto-Friendly",
      "High-Protein",
      "Organic Options",
      "Raw Foods",
      "Fresh Juices",
    ],
  },
  {
    name: "Street Food",
    type: "FOOD",
    subCategories: [
      "Chaat",
      "Pani Puri",
      "Vada Pav",
      "Pav Bhaji",
      "Dosa",
      "Idli",
      "Pakora",
      "Bhel Puri",
      "Kebab Roll",
      "Kati Roll",
    ],
  },
  {
    name: "Noodles",
    type: "FOOD",
    subCategories: [
      "Ramen",
      "Udon",
      "Soba",
      "Lo Mein",
      "Pad Thai",
      "Pho",
      "Chow Mein",
      "Singapore Noodles",
      "Dan Dan Noodles",
      "Cold Noodles",
    ],
  },
  {
    name: "Dumplings",
    type: "FOOD",
    subCategories: [
      "Steamed Dumplings",
      "Fried Dumplings",
      "Soup Dumplings",
      "Gyoza",
      "Potstickers",
      "Momo",
      "Wonton",
      "Shumai",
      "Bao",
      "Dumpling Platter",
    ],
  },
  {
    name: "Bakery",
    type: "DESSERT",
    subCategories: [
      "Croissants",
      "Muffins",
      "Scones",
      "Danish",
      "Donuts",
      "Bagels",
      "Cupcakes",
      "Pastries",
      "Cookies",
      "Bread Loaves",
    ],
  },
  {
    name: "Middle Eastern",
    type: "FOOD",
    subCategories: [
      "Shawarma",
      "Falafel",
      "Hummus",
      "Kebab",
      "Gyro",
      "Baba Ghanoush",
      "Tabbouleh",
      "Fattoush",
      "Kofta",
      "Mezze Platter",
    ],
  },
  {
    name: "Latin American",
    type: "FOOD",
    subCategories: [
      "Empanadas",
      "Arepas",
      "Ceviche",
      "Churrasco",
      "Tamales",
      "Pupusas",
      "Ropa Vieja",
      "Arroz con Pollo",
      "Chimichurri",
      "Latin Platter",
    ],
  },
  {
    name: "Mediterranean",
    type: "FOOD",
    subCategories: [
      "Greek Salad",
      "Moussaka",
      "Souvlaki",
      "Spanakopita",
      "Dolmades",
      "Mediterranean Bowl",
      "Grilled Octopus",
      "Greek Platter",
      "Tzatziki",
      "Pita Bread",
    ],
  },
  {
    name: "Wings",
    type: "FOOD",
    subCategories: [
      "Buffalo Wings",
      "BBQ Wings",
      "Honey Garlic",
      "Teriyaki Wings",
      "Lemon Pepper",
      "Spicy Wings",
      "Garlic Parmesan",
      "Sweet Chili",
      "Dry Rub",
      "Wing Platter",
    ],
  },
  {
    name: "Hot Dogs",
    type: "FOOD",
    subCategories: [
      "Classic Hot Dog",
      "Chili Dog",
      "Chicago Dog",
      "New York Dog",
      "Corn Dog",
      "Sausage Dog",
      "Veggie Dog",
      "Gourmet Hot Dog",
      "Hot Dog Combo",
      "Mini Dogs",
    ],
  },
  {
    name: "Wraps",
    type: "FOOD",
    subCategories: [
      "Chicken Wrap",
      "Veggie Wrap",
      "Falafel Wrap",
      "Caesar Wrap",
      "Buffalo Wrap",
      "Greek Wrap",
      "Turkey Wrap",
      "Tuna Wrap",
      "Shawarma Wrap",
      "Breakfast Wrap",
    ],
  },
  {
    name: "Bowl Meals",
    type: "FOOD",
    subCategories: [
      "Rice Bowl",
      "Poke Bowl",
      "Buddha Bowl",
      "Burrito Bowl",
      "Quinoa Bowl",
      "Noodle Bowl",
      "Grain Bowl",
      "Acai Bowl",
      "Smoothie Bowl",
      "Power Bowl",
    ],
  },
  {
    name: "Brunch",
    type: "FOOD",
    subCategories: [
      "Avocado Toast",
      "Shakshuka",
      "Eggs Benedict",
      "Brunch Burger",
      "Smoked Salmon",
      "Brunch Platter",
      "Belgian Waffles",
      "Crepes",
      "Quiche",
      "Frittata",
    ],
  },
  {
    name: "Fried Chicken",
    type: "FOOD",
    subCategories: [
      "Southern Fried",
      "Nashville Hot",
      "Korean Fried",
      "Chicken Tenders",
      "Popcorn Chicken",
      "Chicken Drumsticks",
      "Chicken Sandwich",
      "Fried Chicken Combo",
      "Chicken & Waffles",
      "Bucket Meal",
    ],
  },
  {
    name: "Frozen Treats",
    type: "DESSERT",
    subCategories: [
      "Ice Cream Sundae",
      "Gelato",
      "Sorbet",
      "Frozen Yogurt",
      "Ice Cream Sandwich",
      "Milkshake",
      "Float",
      "Popsicle",
      "Snow Cone",
      "Affogato",
    ],
  },
  {
    name: "Specialty Drinks",
    type: "DRINK",
    subCategories: [
      "Bubble Tea",
      "Fresh Lime Soda",
      "Lassi",
      "Coconut Water",
      "Iced Coffee",
      "Frappe",
      "Horchata",
      "Thai Tea",
      "Matcha Latte",
      "Specialty Shakes",
    ],
  },
  {
    name: "Platters & Sharing",
    type: "FOOD",
    subCategories: [
      "Appetizer Platter",
      "Seafood Platter",
      "Mezze Platter",
      "BBQ Platter",
      "Dessert Platter",
      "Party Tray",
      "Family Pack",
      "Sampler",
      "Combo Platter",
      "Sharing Board",
    ],
  },
  {
    name: "Low-Calorie",
    type: "FOOD",
    subCategories: [
      "Grilled Salad",
      "Steamed Vegetables",
      "Grilled Fish",
      "Soup",
      "Fruit Bowl",
      "Light Sandwich",
      "Protein Plate",
      "Veggie Stir Fry",
      "Light Pasta",
      "Diet Special",
    ],
  },
  {
    name: "Cheese Specialties",
    type: "FOOD",
    subCategories: [
      "Cheese Pizza",
      "Mac & Cheese",
      "Grilled Cheese",
      "Cheese Platter",
      "Fondue",
      "Quesadilla",
      "Cheese Fries",
      "Mozzarella Sticks",
      "Cheese Board",
      "Four Cheese Pasta",
    ],
  },
  {
    name: "Seasonal Specials",
    type: "FOOD",
    subCategories: [
      "Summer Special",
      "Winter Warmer",
      "Spring Fresh",
      "Fall Favorites",
      "Holiday Special",
      "Limited Time Offer",
      "Chef's Special",
      "Daily Special",
      "Weekend Special",
      "Monthly Feature",
    ],
  },
  {
    name: "Gourmet",
    type: "FOOD",
    subCategories: [
      "Gourmet Burger",
      "Gourmet Pizza",
      "Fine Dining",
      "Tasting Menu",
      "Chef's Plate",
      "Premium Steak",
      "Truffle Dishes",
      "Caviar",
      "Foie Gras",
      "Luxury Platter",
    ],
  },
  {
    name: "Comfort Food",
    type: "FOOD",
    subCategories: [
      "Pot Pie",
      "Meatloaf",
      "Casserole",
      "Shepherd's Pie",
      "Chicken & Dumplings",
      "Goulash",
      "Beef Stew",
      "Roast Dinner",
      "Gravy & Biscuits",
      "Home Style Platter",
    ],
  },
  {
    name: "International Cuisine",
    type: "FOOD",
    subCategories: [
      "French Cuisine",
      "Italian Cuisine",
      "Japanese Cuisine",
      "Chinese Cuisine",
      "Thai Cuisine",
      "Korean Cuisine",
      "Vietnamese Cuisine",
      "Spanish Cuisine",
      "Turkish Cuisine",
      "World Platter",
    ],
  },
  {
    name: "Finger Foods",
    type: "FOOD",
    subCategories: [
      "Chicken Nuggets",
      "Sliders",
      "Mini Tacos",
      "Popcorn Chicken",
      "Cheese Balls",
      "Mini Quiche",
      "Finger Sandwiches",
      "Bite-Size Appetizers",
      "Party Snacks",
      "Finger Food Platter",
    ],
  },
];

export async function seedMenuCategories() {
  console.log("Starting menu category seeding...");

  try {
    for (const catData of categoryData) {
      const categorySlug = createSlug(catData.name);

      // Upsert main category (idempotent)
      const category = await prisma.category.upsert({
        where: { slug: categorySlug },
        update: {
          name: catData.name,
          type: catData.type,
          isActive: true,
        },
        create: {
          name: catData.name,
          slug: categorySlug,
          type: catData.type,
          isActive: true,
          isDemo: false,
        },
      });

      console.log(`✓ Category: ${category.name}`);

      // Upsert subcategories (idempotent)
      for (let i = 0; i < catData.subCategories.length; i++) {
        const subCatName = catData.subCategories[i];
        const subCatSlug = createSlug(subCatName);

        await prisma.subCategory.upsert({
          where: {
            categoryId_slug: {
              categoryId: category.id,
              slug: subCatSlug,
            },
          },
          update: {
            name: subCatName,
            isActive: true,
            displayOrder: i,
          },
          create: {
            categoryId: category.id,
            name: subCatName,
            slug: subCatSlug,
            isActive: true,
            displayOrder: i,
            isDemo: false,
          },
        });
      }

      console.log(
        `  ✓ Added ${catData.subCategories.length} subcategories`
      );
    }

    // Count totals
    const categoryCount = await prisma.category.count();
    const subCategoryCount = await prisma.subCategory.count();

    console.log("\n=== Seeding Complete ===");
    console.log(`Total Main Categories: ${categoryCount}`);
    console.log(`Total Sub Categories: ${subCategoryCount}`);
    console.log("=========================\n");

    return { categoryCount, subCategoryCount };
  } catch (error) {
    console.error("Error seeding menu categories:", error);
    throw error;
  }
}

// Auto-run seed when executed directly
seedMenuCategories()
  .then(() => {
    console.log("Seed completed successfully");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
